name: Android CI

on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout
            uses: actions/checkout@v2.4.0
          
          - name: Setup JDK
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          
          - name: Go to project directory
            run: cd ./Danger
        
          - name: Set execution flag for gradlew
            run: chmod +x ./gradlew
   
          - name: Build with Gradle
            run: ./gradlew build
